# Generated by Django 2.2.12 on 2022-02-02 01:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, db_column='birthday', max_length=255, null=True, verbose_name='Aniversário'),
        ),
        migrations.AddField(
            model_name='user',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', default=datetime.datetime(2022, 2, 2, 1, 54, 9, 323392, tzinfo=utc), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Mas', 'Masculino'), ('Fem', 'Feminino')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, db_column='phoneNumber', max_length=30, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='user',
            name='updatedat',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
